package tugbes;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class TuBes extends javax.swing.JFrame {
    String[] data;
    String url;
    File file;
    BufferedReader br;
    String path;
    BufferedWriter bw;
    DefaultTableModel model1;//untuk jTable1
    DefaultTableModel model2;//untuk jTable2
    int d = 0, total = 0, kembali = 0;

    public TuBes() {
        initComponents();
        model1 = (DefaultTableModel)jTable1.getModel();
        model2 = (DefaultTableModel)jTable2.getModel();
        loadData();
        totalfield.setEnabled(false);
        kembalian.setEnabled(false);
        paket.setEnabled(false);
        jenispaket.setEnabled(false);
        harga.setEnabled(false);
    }
    public void loadData() {
        url = "src/tugbes/Laundry.txt";
        file = new File (url);
        try {
            br = new BufferedReader(new FileReader(file));
//            String barisPertama = br.readLine();
//            String[] namaKolom = barisPertama.split(",");
//            model1 = (DefaultTableModel) jTable1.getModel();
//            model1.setColumnIdentifiers(namaKolom);
            
            Object[]dataBaris = br.lines().toArray();
            for(int i = 0; i<dataBaris.length;i++){
                String baris = dataBaris[i].toString();
                String[] data = baris.split("/");
                model1.addRow(data);
            }
        } catch (Exception e) {
        }
    }
    public void Update(){
        path = "src/tugbes/Laundry.txt";
        file = new File(path);
        try {
            bw = new BufferedWriter(new FileWriter(file));
            for(int i=0;i<jTable1.getRowCount();i++){
                for(int j=0;j<jTable1.getColumnCount();j++){
                    if(j>0)
                        bw.write("/");
                    bw.write(jTable1.getValueAt(i, j).toString());
                }
                bw.newLine();
            }
            bw.close();
        } catch (IOException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jPanel1 = new tugbes.image();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        paket = new javax.swing.JTextField();
        jenispaket = new javax.swing.JTextField();
        kg = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        totalfield = new javax.swing.JTextField();
        cash = new javax.swing.JTextField();
        kembalian = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PAKET", "JENIS PAKET", "HARGA", "SATUAN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 390, 190);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Paket", "Jenis Paket", "Kg", "Harga", "Total Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 250, 390, 270);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Paket");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(490, 30, 50, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Jenis Paket");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(490, 70, 70, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Kg");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(490, 110, 20, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Harga");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(490, 150, 40, 20);
        jPanel1.add(paket);
        paket.setBounds(590, 30, 140, 30);

        jenispaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenispaketActionPerformed(evt);
            }
        });
        jPanel1.add(jenispaket);
        jenispaket.setBounds(590, 70, 140, 30);

        kg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kgKeyTyped(evt);
            }
        });
        jPanel1.add(kg);
        kg.setBounds(590, 110, 140, 30);

        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });
        jPanel1.add(harga);
        harga.setBounds(590, 150, 140, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Total Bayar");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(480, 300, 80, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Cash");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(480, 350, 60, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Kembalian");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(480, 400, 70, 15);
        jPanel1.add(totalfield);
        totalfield.setBounds(610, 300, 110, 30);
        jPanel1.add(cash);
        cash.setBounds(610, 340, 110, 30);
        jPanel1.add(kembalian);
        kembalian.setBounds(610, 380, 110, 30);

        jButton1.setText("BAYAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(680, 443, 80, 30);

        jButton2.setText("PESAN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(680, 200, 80, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here
        paket.setText("");
        paket.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        jenispaket.setText("");
        jenispaket.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
        harga.setText("");
        harga.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void kgKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kgKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_kgKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//         TODO add your handling code here:
         String [] data2 = new String [5];
        String pkt = paket.getText();
        String jpkt = jenispaket.getText();
        String hrg = harga.getText();
        int hargaaa = Integer.parseInt(harga.getText());
        int jumlah = Integer.parseInt(kg.getText());
        
        int h = 0,  baris = 0;
        String nama = "";
        boolean ada = false;
        if(pkt.equals("") || jumlah == 0 ){
            
        }
        else{
            for(int i = 0; i<model1.getRowCount();i++){
                if(pkt.equals(model1.getValueAt(i, 0))){
                    nama = model1.getValueAt(i, 1).toString();
                    hrg = model1.getValueAt(i, 2).toString();
                    
                    
                    
                    
                    baris = i;
                    ada = true;
                    paket.setText("");  
                    jenispaket.setText("");
                    kg.setText("");
                    harga.setText("");
                            
                }
            }
            
                Update();
                loadData();
                data2 [0] = pkt;
                data2 [1] = jpkt;
                data2 [2] = ""+jumlah;
                data2 [3] = hrg;
                data2 [4] = ""+(hargaaa*jumlah);
                
                model2.addRow(data2);
           
           
        }
        total += (hargaaa*jumlah);
        totalfield.setText("Rp. "+total);

          //  DefaultTableModel model = (DefaultTableModel)jTable2.getModel ();
            //model.addRow(new Object []{paket.getText(),jenispaket.getText(),kg.getText(),harga.getText()});
//        int a = Integer.parseInt(kg.getText());
//        int b = Integer.parseInt(harga.getText());
//        int c = a*b;
//
//        DefaultTableModel tb = (DefaultTableModel)jTable2 .getModel ();
//        Vector z = new Vector ();
//        z.add(paket.getText());
//        z.add(jenispaket.getText());
//        z.add(harga.getText());
//        z.add(kg.getText());
//        z.add(c)
//        tb.addRow(z);
//    
//        int total = (harga*kg);
//        totalfield.setText("Rp. "+total);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jenispaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenispaketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenispaketActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          if(cash.getText().isEmpty()){
            
            
        }
        else{
            int uang = Integer.parseInt(cash.getText().toString());
            kembali = uang - total;
            if(total != 0){
                if(uang >= total){
                    kembalian.setText("Rp. "+ kembali);
                }
                else{
                   // kembaliField.setText("Uang Kurang");
                   JOptionPane.showMessageDialog(null,"Uang Kurang","Perhatian",HEIGHT);
                }
            }
            else{
                kembalian.setText("Rp. "+ uang);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TuBes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TuBes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TuBes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TuBes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TuBes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cash;
    private javax.swing.JTextField harga;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jenispaket;
    private javax.swing.JTextField kembalian;
    private javax.swing.JTextField kg;
    private javax.swing.JTextField paket;
    private javax.swing.JTextField totalfield;
    // End of variables declaration//GEN-END:variables
}
